"use client";

import { ChevronDown, Download, FileText } from "lucide-react";

import {
  GENERATED_REPORTS,
  type ReportStatus,
} from "@/lib/mock-data/intelligence";

const STATUS_BADGE_CLASS: Record<ReportStatus, string> = {
  Ready: "border-[#009061] bg-[#ecfff8] text-[#009061]",
  Scheduled: "border-[#cc8000] bg-[#fff6e6] text-[#cc8000]",
  Generating: "border-[#9ca3af] bg-[#f3f4f6] text-[#6b7280]",
};

function FilterButton({ label }: { label: string }) {
  return (
    <button className="flex items-center gap-1.5 rounded-lg border border-[#e6ebf3] bg-white px-3 py-2 font-[family-name:var(--font-urbanist)] text-sm text-[#6b7280] hover:border-[#3b2513] hover:text-[#3b2513]">
      {label}
      <ChevronDown className="h-4 w-4" />
    </button>
  );
}

export function ReportsTab() {
  return (
    <div className="flex flex-col gap-4">
      <div className="flex justify-end">
        <button className="rounded-lg bg-[#3b2513] px-4 py-2 font-[family-name:var(--font-nunito)] text-sm font-medium text-[#faf2e1]">
          Generate Report
        </button>
      </div>

      <div className="overflow-hidden rounded-xl bg-white shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-3 p-4">
          <h2 className="font-[family-name:var(--font-merriweather)] text-lg font-bold text-[#2d1810]">
            Generated Reports
          </h2>
          <div className="flex items-center gap-2">
            <FilterButton label="All Types" />
            <FilterButton label="All Status" />
          </div>
        </div>
        <div className="hidden overflow-x-auto lg:block">
          <table className="w-full text-left">
            <thead>
              <tr className="bg-[#edd9c0]">
                {["Report", "Type", "File", "Generated On", "Generated By", "Status", "Action"].map((h) => (
                  <th key={h} className="px-4 py-3 text-xs font-semibold font-[family-name:var(--font-nunito)] text-[#2d1810]">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-[#eaecf0]">
              {GENERATED_REPORTS.map((r) => (
                <tr key={r.id} className="hover:bg-[#faf9f7]">
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <FileText className="size-3.5 text-[#3b2513]" />
                      <span className="font-[family-name:var(--font-nunito)] text-sm font-semibold text-[#2d1810]">
                        {r.title}
                      </span>
                    </div>
                  </td>
                  <td className="px-4 py-3 font-[family-name:var(--font-nunito)] text-sm text-[#454b54]">{r.type}</td>
                  <td className="px-4 py-3 font-[family-name:var(--font-nunito)] text-sm text-[#454b54]">{r.fileType}</td>
                  <td className="px-4 py-3 font-[family-name:var(--font-nunito)] text-sm text-[#454b54]">{r.generatedOn}</td>
                  <td className="px-4 py-3 font-[family-name:var(--font-nunito)] text-sm text-[#454b54]">{r.generatedBy}</td>
                  <td className="px-4 py-3">
                    <span className={`inline-flex items-center rounded-full border px-2.5 py-0.5 font-[family-name:var(--font-urbanist)] text-xs ${STATUS_BADGE_CLASS[r.status]}`}>
                      {r.status}
                    </span>
                  </td>
                  <td className="px-4 py-3">
                    {r.status === "Ready" && (
                      <button className="flex items-center gap-1.5 text-[#3b2513] hover:opacity-70">
                        <Download className="size-3.5" />
                        <span className="font-[family-name:var(--font-urbanist)] text-xs">Download</span>
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {/* Mobile card list */}
        <div className="flex flex-col gap-2 p-4 lg:hidden">
          {GENERATED_REPORTS.map((r) => (
            <div key={r.id} className="rounded-xl border border-[#eaecf0] p-3">
              <div className="flex items-center justify-between">
                <p className="text-sm font-bold font-[family-name:var(--font-nunito)] text-[#2d1810]">{r.title}</p>
                <span className={`inline-flex items-center rounded-full border px-2.5 py-0.5 font-[family-name:var(--font-urbanist)] text-xs ${STATUS_BADGE_CLASS[r.status]}`}>
                  {r.status}
                </span>
              </div>
              <p className="mt-1 font-[family-name:var(--font-nunito)] text-xs text-[#6b7280]">
                {r.type} • {r.fileType} • {r.generatedOn}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
